//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvisionPhonebook.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKisi
    {
        public int KisiID { get; set; }
        public string KisiAd { get; set; }
        public string KisiSoyad { get; set; }
        public string KisiTel { get; set; }
        public string KisiTelTip { get; set; }
    }
}
